schema_version = "1.0.0"

id = "mt"
version = "0.37.93"
name = "MekTools"
tagline = "Tools To Apply the MekRig"
maintainer = "G3ru1a <egidiufarcas@maze.ws>"
type = "add-on"

permissions = ["files", "network"]

blender_version_min = "4.0.0"

license = [
  "SPDX:GPL-3.0",
]

wheels = [
    "./wheels/PyYAML-6.0.2-cp311-cp311-win_amd64.whl",
    "./wheels/PyYAML-6.0.2-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
]