name: "MekTools"
id_name: "mt"
author: "G3ru1a, Meku Maki, Skulblaka, ThetaFive"
version: [0, 37, 95]
blender: [4, 0, 0]
location: "View3D > UI > Mektools"
description: "Helpful tools for importing FFXIV Characters for quick display and character animating and rendering"
warning: ""
doc_url: ""
category: "MT DEV"
custom_shapes_filename: "MekShapes.blend"
yaml_files_folder: "dump"
rig_master_files: "rig_configurations"
production: false
armature_constraint_name_placeholder: "character_armature"
created_bones_collection_name: "CREATED"

variants: 
  - ['default', "Default", "Default Values"]
  - ['roegadyn_male', "Roegadyn Male", "Write Variants for Roegadyn"]
  - ['roegadyn_female', "Roegadyn Female", "Write Variants for Roegadyn"]
  - ['hrothgar_male', "Hrothgar Male", "Write Variants for Hrothgar"]
  - ['hrothgar_female', "Hrothgar Female", "Write Variants for Hrothgar"]
  - ['lalafell_male', "Lalafell Male", "Write Variants for Lalafell"]
  - ['lalafell_female', "Lalafell Female", "Write Variants for Lalafell"]
  - ['viera_male', "Viera Male", "Write Variants for Viera"]
  - ['viera_female', "Viera Female", "Write Variants for Viera"]
  - ['elezen_male', "Elezen Male", "Write Variants for Elezen"]
  - ['elezen_female', "Elezen Female", "Write Variants for Elezen"]
  - ['aura_male', "Au Ra Male", "Write Variants for Au Ra"]
  - ['aura_female', "Au Ra Female", "Write Variants for Au Ra"]
  - ['miqote_male', "Miqo'te Male", "Write Variants for Miqo'te"]
  - ['miqote_female', "Miqo'te Female", "Write Variants for Miqo'te"]
  - ['midlander_male', "Midlander Male", "Write Variants for Midlander"]
  - ['midlander_female', "Midlander Female", "Write Variants for Midlander"]
  - ['highlander_male', "Highlander Male", "Write Variants for Highlander"]
  - ['highlander_female', "Highlander Female", "Write Variants for Highlander"]
